# Generated by Django 3.2.25 on 2024-06-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.choice'),
        ),
    ]
