# Generated by Django 3.2.25 on 2024-06-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_choice_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monitoring_threshold',
            field=models.FloatField(default=38.4),
        ),
        migrations.AddField(
            model_name='category',
            name='normal_threshold',
            field=models.FloatField(default=47),
        ),
    ]
